# Uncomment this line to define a global platform for your project
platform :ios, '6.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'YJPageView' do
    
    pod 'YJPageView'

end

target 'YJPageViewTests' do

end

target 'YJPageViewUITests' do

end

